export default {
  index: 'All credential types',
  'email-imap': 'Email - IMAP',
  'email-smtp': 'Email - SMTP',
  'google-oauth': 'Google OAuth',
  'microsoft-oauth': 'Microsoft OAuth',
  'ftp-sftp': 'FTP/SFTP',
  'postgresql': 'Postgre SQL',
  'sql-server': 'SQL Server',
  'sql-server-ssrs': 'SQL Server - SSRS',
  'ssrs-server-address': 'SSRS Server Address',
  'http-https': 'HTTP/HTTPs',
  'login': 'Login',
  'microsoft-rdp': 'Microsoft Remote Desktop',
  'unix-ssh': 'Unix / SSH',
  'amazon-iam': 'Amazon Identity Access Management',
  'backstop': 'Backstop',
  'bloomberg': 'Bloomberg',
  'eze-analytics-interface': 'EZE Analytics Interface',
  'geneva': 'Geneva',
  'maps-interface': 'MAPS Interface',
  's3-blacklight': 'S3 Partners - Blacklight',
  'microsoft-power-bi': 'Microsoft Power BI',
  'power-bi-server-address': 'Power BI Server Address',
  'open-data': 'Open Data',
  'egnyte': 'Egnyte Cloud Storage Platform',
}
