export default {
  'data-request-task': 'Data request task',
  email: 'Email',
  'email-check': 'Email Check',
  'ftp-download': 'FTP Download',
  'ftp-monitor': 'FTP Monitor',
  'ftp-transmit': 'FTP Transmit',
  'http-https-download': 'HTTP/HTTPs Download',
  'open-data-job': 'Open Data Job',
  'pdf-scraper': 'PDF Scraper',
  'quick-email-monitor': 'Quick Email Monitor',
  'quick-task': 'Quick Task',
  task: 'Task',
  'unix-command': 'Unix Command',
  'aws-automation-job': 'AWS Automation Job',
  'batch-file': 'Batch File',
  'compress-files': 'Compress Files',
  'convert-csv-to-excel': 'Convert CSV to Excel',
  'convert-excel-to-csv': 'Convert Excel to CSV',
  'convert-pdf-to-text': 'Convert PDF to Text',
  'decompress-files': 'Decompress Files',
  'decrypt-file-pgp': 'Decrypt File - PGP',
  'decrypt-file-rsa': 'Decrypt File - RSA',
  'encrypt-file-pgp': 'Encrypt File - PGP',
  'encrypt-file-rsa': 'Encrypt File - RSA',
  'file-action': 'File Action',
  'file-monitor': 'File Monitor',
  'unix-health-monitor': 'Unix Health Monitor',
  'xsl-transform': 'XSL Transform',
  'data-review-task': 'Data Review Task',
  'etl-job': 'ETL Job',
  'power-bi-to-file': 'Power BI to File',
  'sql-bulk-load': 'SQL Bulk Load',
  'sql-text-procedure': 'SQL Text/Procedure',
  'ssis-package': 'SSIS Package',
  'ssrs-report-run': 'SSRS Report Run',
  'table-to-csv': 'Table to CSV',
  'aga-sync': 'Aga Sync',
  'backstop-to-file': 'Backstop to File',
  'bloomberg-historical-to-file': 'Bloomberg Historical to File',
  'bloomberg-to-file': 'Bloomberg to File',
  'custom-bloomberg-to-file': 'Custom Bloomberg to File',
  'eze-analytics-api-to-file': 'Eze Analytics API to File',
  'geneva-loader': 'Geneva Loader',
  'geneva-query-to-file': 'Geneva Query to File',
  'geneva-rsl-to-file': 'Geneva RSL to File',
  'geneva-security-check': 'Geneva Security Check',
  'global-relay-smtp-archive': 'Global Relay SMTP Archive',
  'maps-api': 'MAPS API',
  'run-rep-rsl': 'Run Rep RSL',
  's3-blacklight-to-file': 'S3 Blacklight to File',
  'demo-job': 'Demo Job',
  group: 'Group',
  'web-watcher': 'Web Watcher'
}
